# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Simulado', max_length=255)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('em_andamento', 'Em andamento'), ('finalizado', 'Finalizado')], default='rascunho', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=20)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('tempo_limite_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('tempo_usado_segundos', models.PositiveIntegerField(default=0)),
                ('total_acertos', models.PositiveIntegerField(default=0)),
                ('total_erros', models.PositiveIntegerField(default=0)),
                ('percentual', models.FloatField(default=0.0)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'simulado',
                'verbose_name_plural': 'simulados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SimuladoQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('letra_escolhida', models.CharField(blank=True, default='', max_length=1)),
                ('correta', models.BooleanField(blank=True, null=True)),
                ('respondida_em', models.DateTimeField(blank=True, null=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulado_itens', to='questions.questao')),
                ('simulado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='simulados.simulado')),
            ],
            options={
                'verbose_name': 'questão do simulado',
                'verbose_name_plural': 'questões do simulado',
                'ordering': ['ordem'],
                'unique_together': {('simulado', 'questao')},
            },
        ),
    ]
