# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('orgao', models.CharField(blank=True, default='', max_length=255)),
                ('cargo', models.CharField(blank=True, default='', max_length=255)),
                ('data_prova', models.DateField(blank=True, null=True)),
                ('banca', models.CharField(blank=True, default='', max_length=100)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='concurso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'concurso',
                'verbose_name_plural': 'concursos',
            },
        ),
        migrations.CreateModel(
            name='MetaEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questoes_dia', models.PositiveIntegerField(default=50)),
                ('questoes_semana', models.PositiveIntegerField(default=250)),
                ('horas_estudo', models.DecimalField(decimal_places=1, default=2.0, max_digits=4)),
                ('percentual_acerto_desejado', models.PositiveIntegerField(default=80)),
                ('disciplinas_prioritarias', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meta',
                'verbose_name_plural': 'metas',
            },
        ),
    ]
