# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversaIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, default='Nova conversa', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversas_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversa IA',
                'verbose_name_plural': 'conversas IA',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MensagemIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuário'), ('assistant', 'Assistente'), ('system', 'Sistema')], max_length=20)),
                ('conteudo', models.TextField()),
                ('fontes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='ai.conversaia')),
            ],
            options={
                'verbose_name': 'mensagem IA',
                'verbose_name_plural': 'mensagens IA',
                'ordering': ['created_at'],
            },
        ),
    ]
