# Generated by Django 5.2.16 on 2026-08-12 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_questao_banca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=8, unique=True)),
                ('modo', models.CharField(choices=[('1x1', '1 contra 1'), ('todos', 'Todos contra todos')], default='todos', max_length=10)),
                ('status', models.CharField(choices=[('lobby', 'Lobby'), ('question', 'Questão'), ('reveal', 'Revelação'), ('finished', 'Finalizada'), ('cancelada', 'Cancelada')], default='lobby', max_length=20)),
                ('quantidade', models.PositiveIntegerField(default=10)),
                ('tempo_por_questao', models.PositiveIntegerField(default=20)),
                ('filtros', models.JSONField(blank=True, default=dict)),
                ('indice_atual', models.PositiveIntegerField(default=0)),
                ('fase_iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_host', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sala de competição',
                'verbose_name_plural': 'salas de competição',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=32)),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('is_host', models.BooleanField(default=False)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('acertos', models.PositiveIntegerField(default=0)),
                ('tempo_total_ms', models.PositiveIntegerField(default=0)),
                ('conectado_em', models.DateTimeField(auto_now_add=True)),
                ('ultimo_ping', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participacoes_competicao', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='competicoes.salacompeticao')),
            ],
            options={
                'verbose_name': 'participante',
                'verbose_name_plural': 'participantes',
                'ordering': ['-pontos', 'tempo_total_ms', 'conectado_em'],
                'unique_together': {('sala', 'apelido')},
            },
        ),
        migrations.CreateModel(
            name='SalaQuestao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competicao_itens', to='questions.questao')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='competicoes.salacompeticao')),
            ],
            options={
                'verbose_name': 'questão da sala',
                'verbose_name_plural': 'questões da sala',
                'ordering': ['ordem'],
                'unique_together': {('sala', 'ordem')},
            },
        ),
        migrations.CreateModel(
            name='RespostaCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(blank=True, default='', max_length=1)),
                ('correta', models.BooleanField(default=False)),
                ('pontos', models.PositiveIntegerField(default=0)),
                ('tempo_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='competicoes.participante')),
                ('sala_questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='competicoes.salaquestao')),
            ],
            options={
                'verbose_name': 'resposta da competição',
                'verbose_name_plural': 'respostas da competição',
                'unique_together': {('sala_questao', 'participante')},
            },
        ),
    ]
