# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_origem', models.PositiveIntegerField(blank=True, null=True)),
                ('pagina', models.PositiveIntegerField(blank=True, null=True)),
                ('enunciado', models.TextField()),
                ('dificuldade', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Médio'), ('dificil', 'Difícil'), ('nao_informado', 'Não informado')], default='nao_informado', max_length=20)),
                ('gabarito', models.CharField(blank=True, default='', max_length=1)),
                ('explicacao', models.TextField(blank=True, default='')),
                ('origem', models.CharField(choices=[('pdf', 'PDF'), ('ai_generated', 'Gerada por IA')], default='pdf', max_length=20)),
                ('trecho_referencia', models.TextField(blank=True, default='')),
                ('hash_conteudo', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='catalog.assunto')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='catalog.disciplina')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='documents.documento')),
                ('subassunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questoes', to='catalog.subassunto')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['disciplina', 'assunto', 'numero_origem'],
            },
        ),
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1)),
                ('texto', models.TextField()),
                ('correta', models.BooleanField(default=False)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternativas', to='questions.questao')),
            ],
            options={
                'verbose_name': 'alternativa',
                'verbose_name_plural': 'alternativas',
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='QuestaoUsuarioMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorita', models.BooleanField(default=False)),
                ('marcar_revisao', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_metas', to='questions.questao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questao_metas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'meta da questão',
                'verbose_name_plural': 'metas das questões',
            },
        ),
        migrations.CreateModel(
            name='Tentativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra_escolhida', models.CharField(max_length=1)),
                ('correta', models.BooleanField()),
                ('tempo_segundos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alternativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.alternativa')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to='questions.questao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentativas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'tentativa',
                'verbose_name_plural': 'tentativas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['dificuldade'], name='questions_q_dificul_266051_idx'),
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['origem'], name='questions_q_origem_a0ddcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='alternativa',
            unique_together={('questao', 'letra')},
        ),
        migrations.AlterUniqueTogether(
            name='questaousuariometa',
            unique_together={('user', 'questao')},
        ),
        migrations.AddIndex(
            model_name='tentativa',
            index=models.Index(fields=['user', 'questao'], name='questions_t_user_id_4f1e82_idx'),
        ),
        migrations.AddIndex(
            model_name='tentativa',
            index=models.Index(fields=['user', 'correta'], name='questions_t_user_id_2be980_idx'),
        ),
    ]
