# Generated by Django 5.2.16 on 2026-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('documents', '0001_initial'),
        ('questions', '0002_questao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='questao',
            name='banca',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Banca organizadora da questão (ex.: CEBRASPE, IMPAR).', max_length=120),
        ),
        migrations.AddIndex(
            model_name='questao',
            index=models.Index(fields=['banca'], name='questions_q_banca_9a452e_idx'),
        ),
    ]
