# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Assunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assuntos', to='catalog.disciplina')),
            ],
            options={
                'verbose_name': 'assunto',
                'verbose_name_plural': 'assuntos',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('disciplina', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subassunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subassuntos', to='catalog.assunto')),
            ],
            options={
                'verbose_name': 'subassunto',
                'verbose_name_plural': 'subassuntos',
                'ordering': ['ordem', 'nome'],
                'unique_together': {('assunto', 'slug')},
            },
        ),
    ]
