# Generated by Django 5.2.16 on 2026-07-31 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assinatura_status',
            field=models.CharField(choices=[('active', 'Ativa'), ('canceling', 'Cancelamento agendado'), ('canceled', 'Cancelada')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cancelado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='periodo_fim',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='periodo_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plano',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], default='free', max_length=20),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=32)),
                ('plan', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('paid', 'Paga'), ('open', 'Em aberto'), ('void', 'Anulada'), ('refunded', 'Reembolsada')], default='paid', max_length=20)),
                ('issued_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fatura',
                'verbose_name_plural': 'faturas',
                'ordering': ['-issued_at'],
            },
        ),
    ]
