# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, default='')),
                ('icone', models.CharField(blank=True, default='award', max_length=50)),
                ('pontos', models.PositiveIntegerField(default=10)),
            ],
            options={
                'verbose_name': 'conquista',
                'verbose_name_plural': 'conquistas',
            },
        ),
        migrations.CreateModel(
            name='UserConquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conquistada_em', models.DateTimeField(auto_now_add=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='gamification.conquista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conquista do usuário',
                'verbose_name_plural': 'conquistas do usuário',
                'unique_together': {('user', 'conquista')},
            },
        ),
    ]
