# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('arquivo', models.FileField(blank=True, upload_to='pdfs/')),
                ('caminho_origem', models.CharField(blank=True, default='', max_length=1000)),
                ('tipo', models.CharField(choices=[('questoes_basico', 'Questões — Básico'), ('questoes_especifico', 'Questões — Específico'), ('teoria_basico', 'Teoria — Básico'), ('teoria_especifico', 'Teoria — Específico'), ('resumo_basico', 'Resumo — Básico'), ('resumo_especifico', 'Resumo — Específico'), ('outro', 'Outro')], default='outro', max_length=40)),
                ('hash_arquivo', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('total_paginas', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('erro', 'Erro')], default='pendente', max_length=20)),
                ('progresso', models.PositiveIntegerField(default=0)),
                ('mensagem_erro', models.TextField(blank=True, default='')),
                ('questoes_extraidas', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PaginaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('texto', models.TextField(blank=True, default='')),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='documents.documento')),
            ],
            options={
                'verbose_name': 'página',
                'verbose_name_plural': 'páginas',
                'ordering': ['numero'],
                'unique_together': {('documento', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='DocumentoChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice', models.PositiveIntegerField(default=0)),
                ('texto', models.TextField()),
                ('disciplina', models.CharField(blank=True, default='', max_length=255)),
                ('assunto', models.CharField(blank=True, default='', max_length=500)),
                ('embedding_id', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.documento')),
                ('pagina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chunks', to='documents.paginadocumento')),
            ],
            options={
                'verbose_name': 'chunk',
                'verbose_name_plural': 'chunks',
                'ordering': ['documento', 'indice'],
            },
        ),
    ]
