# Generated by Django 5.2.16 on 2026-07-31 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessaoEstudo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('livre', 'Livre'), ('revisao', 'Revisão inteligente'), ('erros', 'Meus erros'), ('simulado', 'Simulado')], default='livre', max_length=20)),
                ('iniciada_em', models.DateTimeField(auto_now_add=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('questoes_ids', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sessão',
                'verbose_name_plural': 'sessões',
                'ordering': ['-iniciada_em'],
            },
        ),
        migrations.CreateModel(
            name='DominioAssunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('dados_insuficientes', 'Dados insuficientes'), ('em_avaliacao', 'Em avaliação'), ('precisa_atencao', 'Precisa de atenção'), ('em_desenvolvimento', 'Em desenvolvimento'), ('conhecimento_intermediario', 'Conhecimento intermediário'), ('bom_dominio', 'Bom domínio'), ('dominio_confirmado', 'Domínio confirmado')], default='dados_insuficientes', max_length=40)),
                ('total_respostas', models.PositiveIntegerField(default=0)),
                ('total_acertos', models.PositiveIntegerField(default=0)),
                ('percentual_acerto', models.FloatField(default=0.0)),
                ('dominio_declarado', models.BooleanField(default=False)),
                ('dominio_comprovado', models.BooleanField(default=False)),
                ('data_confirmacao', models.DateTimeField(blank=True, null=True)),
                ('ultima_revisao', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assunto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to='catalog.assunto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dominios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'domínio',
                'verbose_name_plural': 'domínios',
                'unique_together': {('user', 'assunto')},
            },
        ),
    ]
